# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob

In [4]:
DATA_FOLDER = '../../ADA2017-Tutorials/02 - Intro to pandas/Data/' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [5]:
import glob
from os.path import basename
import os 

data = pd.DataFrame(columns =['name']) 

# For each  MID files
for excel in  glob.glob(DATA_FOLDER+"microbiome/*.xls"): 
    if "meta" not in excel : 
        #get name of file/name of collumn of data
        mid =os.path.splitext(basename(excel))[0]
        # read without header
        subdata  = pd.read_excel(excel,header=None)
        # rename data with mid name
        subdata.columns = ["name",mid]
        # Test if bacteril name is unique, for integirty 
        assert ( any(subdata['name'].duplicated()) == False)
        # we merge the Dataframe with the name for common key, "outer" add the new bacterie
        data = data.merge(subdata,on='name', how='outer')
        # change na by unknowd
        data.fillna("unknows", inplace = True)
        

# set name to index, do no crash , name are unique thanks to assert
data = data.set_index('name')
# sort collumn name
data = data[[cn for cn in  sorted(data.columns) ]]

meta  = pd.read_excel((DATA_FOLDER+"microbiome/metadata.xls"))
meta.fillna("unknows", inplace = True)
# rename collone with data form metadata
data.columns = [i for i in reversed(meta.transpose().values.tolist())]
# name colonum with data from metadata
data.columns.names = [i for i in reversed(meta.transpose().index.values.tolist())]

data.head()

SAMPLE                                                        unknows tissue  \
GROUP                                              EXTRACTION CONTROL  NEC 1
BARCODE                                                          MID1   MID2
name
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...                  7     23
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...                  2      2
Archaea "Crenarchaeota" Thermoprotei Sulfolobal...                  3     10
Archaea "Crenarchaeota" Thermoprotei Thermoprot...                  3      9
Archaea "Euryarchaeota" "Methanomicrobia" Metha...                  7      9

SAMPLE                                                                 \
GROUP                                              Control 1    NEC 2
BARCODE                                                 MID3     MID4
name
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...        14        2
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...   unknows  unknows
Archaea "Crenarchaeota" Thermoprotei Sulfolobal...         4  unknows
Archaea "Crenarchaeota" Thermoprotei Thermoprot...         5  unknows
Archaea "Euryarchaeota" "Methanomicrobia" Metha...         7        1

SAMPLE                                                       stool            \
GROUP                                              Control 2 NEC 1 Control 1
BARCODE                                                 MID5  MID6      MID7
name
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...        28     7         8
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...         3     2         1
Archaea "Crenarchaeota" Thermoprotei Sulfolobal...        14     5         5
Archaea "Crenarchaeota" Thermoprotei Thermoprot...        10     4         5
Archaea "Euryarchaeota" "Methanomicrobia" Metha...        17    12        18

SAMPLE
GROUP                                                 NEC 2 Control 2
BARCODE                                                MID8      MID9
name
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  unknows        16
Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  unknows   unknows
Archaea "Crenarchaeota" Thermoprotei Sulfolobal...        1         6
Archaea "Crenarchaeota" Thermoprotei Thermoprot...  unknows         5
Archaea "Euryarchaeota" "Methanomicrobia" Metha...  unknows        14